services:
  frontend:
    image: node:16  # 使用 Node.js 进行 React 构建
    working_dir: /app
    volumes:
      - ./react-test:/app  # 将项目代码挂载到容器中
    command: sh -c "npm install && npm run build"  # 构建 React 项目
    environment:
      - NODE_ENV=production
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # 将 Nginx 暴露在宿主机的 80 端口
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # 挂载自定义的 Nginx 配置
      - ./react-test/build:/usr/share/nginx/html  # 将 React 构建后的静态文件挂载到 Nginx
    depends_on:
      - frontend