services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/usr/share/nginx/html  # 将构建文件夹挂载到 Nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html  # Nginx 服务器提供的静态资源
    depends_on:
      - frontend